### ISSUE TITLE
Uncaught exception in thread "main"

### ISSUE THREAD

**Issue by ayukays** [legoatoom/ConnectibleChains#12]
I'm trying to make a modpack, got this error when starting the game:

`java.lang.RuntimeException: Failed to read accessWidener file from mod connectiblechains
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:145)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:281)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:90)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:478)
	... 3 more
`

**Mods:**
![image](https://user-images.githubusercontent.com/81534459/149671397-5b3c4de0-cad6-4c58-b04d-64d5f17dac3d.png)

**Console additionally says this:**
![image](https://user-images.githubusercontent.com/81534459/149671486-79260e44-66f3-45f4-9a2d-38282929697b.png)

**Comment by Qendolin** [comment]
Oooh i see better clouds, anyway. Access wideners did not change in 2.0.0 and it seems like the jar was not compiled correctly as the version is `$(version)` (instead of the actual version).

**Comment by Qendolin** [comment]
Did you download the mod from modrinth because I just noticed that a wrong file was the default?

**Comment by ayukays** [comment]
Yes!

**Comment by Qendolin** [comment]
Download it again, I've selected the correct file. @legoatoom it was connectiblechains-2.0.0-sources-dev.jar

**Comment by Qendolin** [comment]
If it works, please confirm so I can close the issue

**Comment by ayukays** [comment]
it's working just fine, thank you very much!
